# Generated by Django 4.2.7 on 2023-11-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='UserImage',
        ),
    ]
